### ISSUE TITLE
IndexError to use classify_with_model.py

### ISSUE THREAD

**Issue by shunlishang** [liza183/ascends-toolkit#1]
Using the IRIS example in the readme file, after train_classifier.py to generate the model, and then I run classify_with_model.py, but I met the following IndexError:

$ classify_with_model.py output/iris\,Model\=RF\,accuracy\=0.9533333333333334\,Scaler\=StandardScaler.pkl data/iris_test_input.csv output/iris_test_prediction.csv --mapping "{'Name': {'Iris-setosa':0, 'Iris-versicolor':1, 'Iris-virginica':2}}"
 
* ASCENDS: Advanced data SCiENce toolkit for Non-Data Scientists
* Classification ML model predictor
 
Traceback (most recent call last):
  File "C:/Anaconda/Scripts/classify_with_model.py", line 103, in <module>
    main(args)
  File "C:/Anaconda/Scripts/classify_with_model.py", line 65, in main
    data[key] = data[key].map(mapping[key])
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by liza183** [comment]
I just took a quick look and made a fix. Would you please test it again with the latest code?

**Comment by shunlishang** [comment]
This error has been resolved, and now it works well using the latest code.

**Comment by liza183** [comment]
Thanks! Please feel free to share your feedback here so that we can track the issues
